### 1.

스러피(Slurpy)란 어떠한 속성이 존재하는 문자열이다. 문자열을 읽어서 스러피가 존재하는지를 판단하는 프로그램을 작성해야 한다.

스럼프(Slump)는 다음 속성을 갖는 문자열이다.

첫 번째 문자가 'D' 또는 'E'이다.
첫 번째 문자 뒤에는 하나 이상의 'F'가 나온다.
하나 이상의 'F' 뒤에는 또 다른 스럼프나 'G'가 온다. 스럼프는 'F' 끝에 오는 스럼프나 'G'로끝난다. 예를 들어, DFFEFFFG는 첫 번째 문자가 'D'로 시작하고 두 개의 'F'가 나오며, 또 다른스럼프 'EFFFG'로 끝난다.
위의 경우가 아니면 스럼프가 아니다.

스림프(Slimp)는 다음 속성을 갖는 문자열이다.

첫 번째 문자는 'A'이다.
두 개의 문자로만 된 스림프면, 두 번째 문자는 'H'이다.
두 개의 문자로 된 스림프가 아니면 다음 형식 중의 하나가 된다.
'A' + 'B' + 스림프 + 'C'. 
'A' + 스럼프 + 'C'.
위의 경우가 아니면 스림프가 아니다.
스러피(Slurpy)는 스림프(Slimp) 뒤에 스럼프(Slump)로 구성되는 문자열이다.

다음은 그 예이다.

Slumps : DFG, EFG, DFFFFFG, DFDFDFDFG, DFEFFFFFG
Not Slumps: DFEFF, EFAHG, DEFG, DG, EFFFFDG
Slimps: AH, ABAHC, ABABAHCC, ADFGC, ADFFFFGC, ABAEFGCC, ADFDFGC
Not Slimps: ABC, ABAH, DFGC, ABABAHC, SLIMP, ADGC
Slurpys: AHDFG, ADFGCDFFFFFG, ABAEFGCCDFEFFFFFG
Not Slurpys: AHDFGA, DFGAH, ABABCC


**입력**

입력될 문자열의 개수를 나타내는 정수 N 이 1 ~ 10의 범위로 우선 입력된다. 다음 줄부터 N개의 문자열이 입력된다. 문자열은 1 ~ 60 개의 알파벳 문자로 구성된다.

**출력**

첫 줄에는 "SLURPYS OUTPUT"을 출력한다. N 개의 문자열 입력에 대해서 각 문자열이 스러피인지를 "YES" 또는 "NO"로 표기한다. 마지막으로 "END OF OUTPUT"를 출력한다.



**Sample Input**

2  
AHDFG  
DFGAH




**Sample Output**

SLURPYS OUTPUT  
YES  
NO  
END OF OUTPUT

# 모르겠다...흑

## 2. 

The number 512 is interesting because it is equal to the sum of its digits raised to some power: 5 + 1 + 2 = 8, and $8^3$ = 512. Another example of a number with this property is 614656 = $28^4$.

We shall define an to be the nth term of this sequence and insist that a number must contain at least two digits to have a sum.

You are given that $a_2$ = 512 and $a_{10} $= 614656.

Find $a_{30}$.

In [69]:
ls = []

for k in range(2, 17):
    for i in range(2, 9*k+1):
        p = 2
        j = i ** p
        while j < 10**k:
            if j >= 10**(k-1):
                ls.append(j)
            p += 1
            j = i ** p
        
        ls = list(set(ls))
ls.sort()


ln = ls
len(ln)

732

In [79]:
new = []

for i in ln:
    ls = []
    n = str(i)
    k = list(n)
    for j in k:
        j = int(j)
        ls.append(j)
        div = sum(ls)
    for nn in range(2, 57):
        if div**nn == i:
            new.append(i)
print(new)
new[29]   ##63의 8제곱

[81, 512, 2401, 4913, 5832, 17576, 19683, 234256, 390625, 614656, 1679616, 17210368, 34012224, 52521875, 60466176, 205962976, 612220032, 8303765625, 10460353203, 24794911296, 27512614111, 52523350144, 68719476736, 271818611107, 1174711139837, 2207984167552, 6722988818432, 20047612231936, 72301961339136, 248155780267521, 3904305912313344]


248155780267521

In [ ]:
new = []

for i in ln:
    ls = []
    n = str(i)
    k = list(n)
    for j in k:
        j = int(j)
        ls.append(j)
        div = sum(ls)
    u = i
    while True:
        if u % div == 0 and u // div == 1:
            new.append(i)
        elif u % div == 0:
            u = i // div
            continue
        else:
            break
            
print(new)
new[29]   ##63의 8제곱

In [63]:
new[1], new[9]

(512, 614656)

In [71]:
63**8

248155780267521

## 3.

아래처럼 6 6이라는 입력을 주면 6 X 6 매트릭스에 나선형 회전을 한 값을 출력해야 한다.

In [3]:
# 6 6

#   0   1   2   3   4   5
#  19  20  21  22  23   6
#  18  31  32  33  24   7
#  17  30  35  34  25   8
#  16  29  28  27  26   9
#  15  14  13  12  11  10

In [221]:
def spiral(i , j):
    k = np.ones([i, j],dtype = 'int')
    if i > j:
        m = round(j/2+0.49)
        check = j          ## check : 행과 열 중 작은 수를 할당
    else:
        m = round(i/2+0.49)
        check = i
    p = 0
    ci = i
    cj = j
    if check % 2 != 0:  ## 행과 열 중 작은 수가 홀수일 때
        for s in range(m):
            k[s][s:s+j] = range(p, p+j)
            k.T[cj-1][s:s+i] = range(p+j-1, p+i+j-1)
            if s == m-1 :
                break
            k[ci-1][s:s+j] = range(p+i+j-2, p+i+2*j-2)[::-1]
            k.T[s][s+1:s+1+i-2] = range(p+i+2*j-2, p+2*i+2*j-4)[::-1]
            p += 2*(i + j -2) 
            i -= 2
            j -= 2
            ci -= 1
            cj -= 1
    else :                        ## 그 외의 경우(둘 중 하나라도 짝수일 때)
        for s in range(m):
            k[s][s:s+j] = range(p, p+j)
            k.T[cj-1][s:s+i] = range(p+j-1, p+i+j-1)
            k[ci-1][s:s+j] = range(p+i+j-2, p+i+2*j-2)[::-1]
            k.T[s][s+1:s+1+i-2] = range(p+i+2*j-2, p+2*i+2*j-4)[::-1]
            p += 2*(i + j -2) 
            i -= 2
            j -= 2
            ci -= 1
            cj -= 1
    print(k)
    
spiral(6, 7)  ###모든 크기 매트릭스 가능


[[ 0  1  2  3  4  5  6]
 [21 22 23 24 25 26  7]
 [20 35 36 37 38 27  8]
 [19 34 41 40 39 28  9]
 [18 33 32 31 30 29 10]
 [17 16 15 14 13 12 11]]


## 4.

다음과 같은 형태의 배열을  

[a1,a2,a3...,an,b1,b2...bn]  

다음과 같은 형태로 바꾸시오  

[a1,b1,a2,b2.....an,bn]  

### 2n 개의 리스트를 1, n+1, 2, n+2, ... , n, 2n  순서로바꾸기

In [219]:
def change_list(arr):
    new_ls = []
    n = len(arr) / 2
    n = int(n)
    for i in range(n):
        new_ls.append(arr[i])
        new_ls.append(arr[n+i])

    return new_ls
    

In [220]:
change_list('ABCDEF'), change_list(range(10))

(['A', 'D', 'B', 'E', 'C', 'F'], [0, 5, 1, 6, 2, 7, 3, 8, 4, 9])