In [1]:
import re
import numpy as np

ls = ['a1','a2','a3','a4','a5','a6','a7','a8','a9','a10','a11','a12',
      'c1','c2','c3','c4','c5','c6','c7','c8','c9','c10','c11','c12',
      'b1','b2','b3','b4','b5','b6','b7','b8','b9','b10','b11','b12',]
di = {}
nls = []
for i in range(len(ls)):
    aa = re.findall('\d', ls[i])
    aa = ''.join(aa)
    di[ls[i]] = aa                   ##숫자뽑아냄 => {밸류 = 숫자}
m = 0
for j in range(len(di)):
    if int(di[ls[j]]) > m:
        m = int(di[ls[j]])            #12 // 숫자반복

for k in range(1, m+1):
    for j in range(len(di)):
        if int(di[ls[j]]) == k:
            nls.append(ls[j])        # 숫자가 작은수부터 밸류를 정렬함
            
mm = int(len(nls)/m)
nnls=[[]]

for i in range(m):
    ls=[]
    for j in range(mm):
        ls.append(nls[mm*i+j])
    ls.sort()
    nnls.append(ls)                   ## 밸류를 문자순대로 정렬함(이미숫자는 정렬됨)
    
nnls =np.hstack(nnls)
print(nnls)

['a1' 'b1' 'c1' 'a2' 'b2' 'c2' 'a3' 'b3' 'c3' 'a4' 'b4' 'c4' 'a5' 'b5' 'c5'
 'a6' 'b6' 'c6' 'a7' 'b7' 'c7' 'a8' 'b8' 'c8' 'a9' 'b9' 'c9' 'a10' 'b10'
 'c10' 'a11' 'b11' 'c11' 'a12' 'b12' 'c12']


In [14]:
r = int(input("insert a number : "))
c = r

aa = np.array([[-1]*r]*c)

rn = 0
cn = 0
t = 0
i = 0

def checkstop(ar,r,c):
    
    isError = False
    if r < 0 or c < 0:
        isError = True
        return isError
    
    try:
        ar[r][c]
    except Exception as e:
        isError = True
    finally:
        return isError
            

while t <= 2*r - 1:        
    if t % 4 == 0:                
        aa[rn][cn] = i        
        if checkstop(aa,rn,cn+1) == True or aa[rn][cn+1] != -1:
            t += 1
        else:
            cn += 1
            i += 1            
        
    if t % 4 == 1:       
        aa[rn][cn] = i
        if checkstop(aa,rn+1,cn) == True or aa[rn+1][cn] != -1:
            t += 1
        else:
            rn += 1
            i += 1         

    if t % 4 == 2:
        aa[rn][cn] = i
        if checkstop(aa,rn,cn-1) == True or aa[rn][cn-1] != -1:
            t += 1
        else:
            cn -= 1
            i += 1                  

    if t % 4 == 3:      
        aa[rn][cn] = i
        if checkstop(aa,rn-1,cn) == True or aa[rn-1][cn] != -1:
            t += 1
        else:
            rn -= 1
            i += 1 
                

print(aa)     
        
        

insert a number : 6
[[ 0  1  2  3  4  5]
 [19 20 21 22 23  6]
 [18 31 32 33 24  7]
 [17 30 35 34 25  8]
 [16 29 28 27 26  9]
 [15 14 13 12 11 10]]


In [26]:
ans = []

for low in range(2, 100):
    for up in range(2, 20):
        s=0
        num = low ** up
        stnum = str(num)
        for i in range(len(stnum)):
            s += int(stnum[i])
        if s == low:
            ans.append(num)  

ans.sort()
ans[29]                                   

248155780267521